[meta]
version = 1
name = "Dracula"
description = "The popular Dracula theme"


[colors.core]
background = "#282A36"
foreground = "#F8F8F2"
secondary_background = "#21222C"
border = "#44475A"
accent = "#8BE9FD"

[colors.accents]
blue = "#8BE9FD"
green = "#50FA7B"
magenta = "#FF79C6"
orange = "#FFB86C"
purple = "#BD93F9"
red = "#FF5555"
yellow = "#F1FA8C"
cyan = "#8BE9FD"
