[meta]
version = 1
name = "Tokyo Night"
description = "A clean, dark theme that celebrates the lights of downtown Tokyo at night"
variant = "dark"

[colors.core]
background = "#1a1b26"
foreground = "#c0caf5"
secondary_background = "#16161e"
border = "#414868"
accent = "#7aa2f7"

[colors.accents]
blue = "#7aa2f7"
green = "#9ece6a"
magenta = "#bb9af7"
orange = "#ff9e64"
purple = "#9d7cd8"
red = "#f7768e"
yellow = "#e0af68"
cyan = "#7dcfff"
